language: php

php:
  - 7.2
  - 7.1
  - nightly

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: SYMFONY_VERSION="^3.0"
    - php: '7.1'
      env: SYMFONY_VERSION="^4.0"
    - php: '7.2'
      env: SYMFONY_VERSION="^4.0"
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  # Don't run with xdebug, and don't error when xdebug isn't installed
  - |
    phpenv config-rm xdebug.ini || true
    if [ "$SYMFONY_VERSION" != "" ]; then
      composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
    fi

install: composer update --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --stop-on-failure --verbose